"""empty message

Revision ID: 0677deee269c
Revises: f5938c4ccd25
Create Date: 2022-03-31 11:44:17.102959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0677deee269c'
down_revision = 'f5938c4ccd25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cart_item', ['product_id'])
    op.drop_constraint('cart_item_product_id_fkey', 'cart_item', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('cart_item_product_id_fkey', 'cart_item', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'cart_item', type_='unique')
    # ### end Alembic commands ###
