"""empty message

Revision ID: 260896aaf702
Revises: ce51f5fbd4ce
Create Date: 2022-03-30 15:41:50.656814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260896aaf702'
down_revision = 'ce51f5fbd4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('cart_id', sa.String(length=100), nullable=True))
    op.drop_constraint('cart_productId_key', 'cart', type_='unique')
    op.create_unique_constraint(None, 'cart', ['cart_id'])
    op.drop_column('cart', 'productId')
    op.drop_column('cart', 'quantity')
    op.add_column('user', sa.Column('user_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'user', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_id')
    op.add_column('cart', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('productId', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart', type_='unique')
    op.create_unique_constraint('cart_productId_key', 'cart', ['productId'])
    op.drop_column('cart', 'cart_id')
    # ### end Alembic commands ###
