"""empty message

Revision ID: 59f4e5be007e
Revises: 260896aaf702
Create Date: 2022-03-30 15:45:54.267634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f4e5be007e'
down_revision = '260896aaf702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('user_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'cart', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'user_id')
    # ### end Alembic commands ###
