"""empty message

Revision ID: be7c8dbe2a29
Revises: a33a6ce4f715
Create Date: 2022-04-08 22:10:15.169497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7c8dbe2a29'
down_revision = 'a33a6ce4f715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='order_pkey'),
    sa.UniqueConstraint('order_id', name='order_order_id_key'),
    sa.UniqueConstraint('user_id', name='order_user_id_key')
    )
    # ### end Alembic commands ###
