"""empty message

Revision ID: eec2d0237f78
Revises: c5c81bf4b255
Create Date: 2022-03-31 16:00:09.652885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec2d0237f78'
down_revision = 'c5c81bf4b255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart_item', 'product_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart_item', 'product_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
