"""empty message

Revision ID: f01fc5fa228b
Revises: 61064da516e0
Create Date: 2022-03-30 10:55:01.042890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f01fc5fa228b'
down_revision = '61064da516e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_constraint('user_public_id_key', 'user', type_='unique')
    op.drop_column('user', 'registered_on')
    op.drop_column('user', 'admin')
    op.drop_column('user', 'email')
    op.drop_column('user', 'public_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('registered_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_public_id_key', 'user', ['public_id'])
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    # ### end Alembic commands ###
